dz_app/dz_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dz_app4.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dz_app/dz_app4/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views
from .views import upload_image, add_user, add_product, product_list, view_cart, add_to_cart, remove_from_cart, home
app_name = 'cart'

urlpatterns = [
    path('', views.index, name='index'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('product-list/', views.product_list, name='product_list'),
    path('dz_app4/add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('view-cart/', views.view_cart, name='view_cart'),
    path('about/', views.about, name='about'),
    path('dz_app4/go/', views.product_list, name="dz_app4/go"),
    path('dz_app4/cart/', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('home/', views.home, name='home'),
    path('add/', add_user, name='add_user'),
    path('admin/dz_app4/user/add/', add_user, name='add_user'),
    path('add_product/', add_product, name='add_product'),
    path('admin/dz_app4/product/add/', add_product, name='add_product'),
    path('update_product/', views.update_product, name='update_product'),
    path('update_client/', views.update_client, name='update_client'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('get_product/<int:pk>', views.get_product, name='get_product'),
    path('get_products/', views.get_products, name='get_products'),
    path('get_users/', views.get_users, name='users'),
    path('user_products/<int:client_id>/<int:days_num>', views.all_user_products, name='all_user_products'),
    path('get_customer_orders/<int:pk>', views.get_customer_orders, name='get_customer_orders'),
    path('get_user_order/<int:product_id>', views.get_user_order, name='get_user_order'),
    path('get_order/<int:pk>', views.get_order, name='get_order'),
    path('get_media/', views.get_media, name='get_media'),
    path('upload_image/<int:product_id>', upload_image, name='upload_image')
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dz_app/dz_app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Заголовок базового шаблона {% endblock %}</title>
</head>
<body>
{% block content %}
<h1>Страница сайта</h1>
<h2>Старт проекта интернет-мазина 4</h2>
<p>Контент...</p>
{% endblock %}
<footer>
    {% block content_footer %}
    <hr>
    <H6>Расзрешено свободное использоание материалов сайта</H6>
    {% endblock %}
</footer>
</body>
</html>

dz_app/dz_app/templates/cart.html
<!DOCTYPE html>

<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		/* Add CSS styles for flex container and items */
		.product-list {
			display: flex;
			flex-wrap: wrap; /* Allow items to wrap to the next row if necessary */
			justify-content: space-between; /* Space items evenly along the main axis */
			list-style: none; /* Remove list styles */
			padding: 0;
		}

		.product-item {
			
			flex: 1; /* Grow to fill available space evenly */
			/* Limit item width to avoid overcrowding */
			margin: 10px; /* Add spacing between items */
			border: 1px solid #ccc; /* Add a border for visual separation */
			padding: 10px;
			text-align: center;
		}

		/* Style the "Buy Now" button */
		.buy-now-button {
			display: block;
			margin-top: 10px;
			background-color: #007bff;
			color: #fff;
			text-decoration: none;
			padding: 5px 10px;
			border-radius: 5px;
		}
	</style>
</head>
<body>
	<h1>Ваши заказы</h1>

	<div class="product-list">
	{% for item in cart_items %}
	<div class="product-item">
		<p>{{ item.product.name }} ({{ item.quantity }})</p>
		<p>Price: ${{ item.product.price }}</p>
		<a href="{% url 'cart:remove_from_cart' item.id %}">Remove</a>
	</div>
	{% empty %}
	<p>Your cart is empty.</p>
	{% endfor %}
	</div>
	<p>Total Price: ${{ total_price }}</p>

	<a href="{% url 'cart:product_list' %}">Продолжить заказ</a>
</body>
</html>

dz_app/dz_app/templates/go.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Меню пиццерии</title>
	<style>
		/* Add CSS styles for flex container and items */
		.product-list {
			display: flex;
			flex-wrap: wrap; /* Allow items to wrap to the next row if necessary */
			justify-content: space-between; /* Space items evenly along the main axis */
			list-style: none; /* Remove list styles */
			padding: 0;
		}

		.product-item {
			flex: 1; /* Grow to fill available space evenly */
			max-width: 30%; /* Limit item width to avoid overcrowding */
			margin: 10px; /* Add spacing between items */
			border: 1px solid #ccc; /* Add a border for visual separation */
			padding: 10px;
			text-align: center;
		}

		/* Style the "Buy Now" button */
		.buy-now-button {
			display: block;
			margin-top: 10px;
			background-color: #007bff;
			color: #fff;
			text-decoration: none;
			padding: 5px 10px;
			border-radius: 5px;
		}
	</style>
</head>
<body>
	<h1>Меню пиццерии</h1>


	<ul class="product-list">
		{% for product in products %}
			<li class="product-item">
				<img src="{{ product.image_field.url }}" alt="{{ product.name }}" width="200" height="150">
				<h2>{{ product.name }}</h2>
				<p>{{ product.description }}</p>
				<p>Стоимость: {{ product.price }} </p>
				<a href="#" class="buy-now-button">Заказать</a>
				<a class="buy-now-button" href="{% url 'cart:add_to_cart' product.id %}">Добавить в корзину</a>

			</li>
		{% endfor %}
	</ul>
</body>
</html>

dz_app/dz_app/templates/login.html
{% extends 'dz_app4/base.html'%}


{% block title %}
Авторизация пользователя

{% endblock %}

{% block content %}
<h2>{{ message }}</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить">
</form>
{% endblock %}

dz_app/dz_app/templates/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
</head>
<body>
    <h1>Product List</h1>
    <ul>
        {% for product in products %}
        <li>
            <h2>{{ product.name }}</h2>
            <p>Description: {{ product.description }}</p>
            <p>Price: ${{ product.price }}</p>
            <form action="{% url 'cart:add_to_cart' product.id %}" method="post">
                {% csrf_token %}
                <button type="submit">Add to Cart</button>
            </form>
        </li>
        {% endfor %}
    </ul>
</body>
</html>


<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Product List</title>-->
<!--</head>-->
<!--<body>-->
<!--    <h1>Product List</h1>-->
<!--    {% for product in products %}-->
<!--        <div>-->
<!--            <h2>{{ product.name }}</h2>-->
<!--            <p>Description: {{ product.description }}</p>-->
<!--            <p>Price: {{ product.price }}</p>-->
<!--            &lt;!&ndash; Form for adding the product to the cart &ndash;&gt;-->
<!--            <form action="{% url 'cart:add_to_cart' product.id %}" method="post">-->
<!--                {% csrf_token %}-->
<!--                <button type="submit">Add to Cart</button><a href="{% url 'cart:login' %}">Login</a>-->

<!--            </form>-->
<!--        </div>-->
<!--    {% endfor %}-->
<!--</body>-->
<!--</html>-->

dz_app/dz_app/templates/registration.html
{% extends 'dz_app4/base.html'%}


{% block title %}
Регистрация нового пользователя
{% endblock %}

{% block content %}
<h2>{{ message }}</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить">
</form>
{% endblock %}